name: vedaapp_mobile
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  retrofit: ^4.0.3
  dio: ^5.3.2
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  flutter_widget_from_html_core: ^0.14.3
  webview_flutter: ^4.4.1
  flutter_html: ^3.0.0-beta.2
  http: ^1.1.0
  go_router: ^12.0.0
  either_dart: ^1.0.0
  json_annotation: ^4.1.0
  get_it: ^7.6.4
  pretty_dio_logger: ^1.3.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
